version: '3'

services: 
  postgres: 
    container_name: mc-db
    build: 
      context: .
      dockerfile: Dockerfile.database
    environment: 
      POSTGRES_USER: salazar
      POSTGRES_PASSWORD: salazar
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: crypto
    ports: 
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ../database/data:/var/lib/postgresql/data